permalink: /:categories/:year-:month/:title.html

pygments: true
paginate: 5

title : MHST14-13-Mizu
author :
  name : Mizu Team
  email : mhst14-13-mizu@googlegroups.com
  github : MHST14-13-Mizu

JB :
  version : 0.3.0

  BASE_PATH : false
  ASSET_PATH : false

  # page
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  rss_path : /rss.xml

  comments :
    provider : false

  cdn :
    jquery :
      js : //cdn.bootcss.com/jquery/2.1.0/jquery.min.js
    webfont : true
    google-fonts :
      js : //cdn.bootcss.com/webfont/1.3.0/webfont.min.js
    font-awesome :
      css : //cdn.bootcss.com/font-awesome/4.0.3/css/font-awesome.min.css
    bootstrap :
      js : //netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js
      css : //netdna.bootstrapcdn.com/bootswatch/3.1.1/cerulean/bootstrap.min.css
    fancybox :
      js : //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.js
      css : //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.css
  blogroll : false
